[package]
name = "snake_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12", features = ["canvas", "tokio", "debug"] }
rand = "0.8"
# tokio is needed for iced::time::every
tokio = { version = "1", features = ["rt", "time"] }